<?xml version="1.0"?>
<package format="2">
  <name>ros1_comm_lab</name>
  <version>0.0.1</version>
  <description>ROS1 roscpp communication, callback, service, action, and testing experiments.</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>

  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>

  <build_export_depend>message_runtime</build_export_depend>
  <exec_depend>message_runtime</exec_depend>

  <test_depend>rostest</test_depend>
</package>
